/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import Clases.*;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author Fabián
 */
public class VentanaIniciarSesion extends javax.swing.JFrame {
     private File plan;
     public static ImageIcon foto = null;
    /**
     * Creates new form VentanaIniciarSesion
     */
    public VentanaIniciarSesion() {
        Image icon = new ImageIcon(getClass().getResource("/Imagenes/world-cup-icon.png")).getImage();
        setIconImage(icon);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondoAzul = new javax.swing.JLabel();
        panelLogIn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textFieldUsuario = new javax.swing.JTextField();
        passwordFieldContraseña = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fondoAzul1 = new javax.swing.JLabel();
        panelRegistro = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        textFieldNuevoNombre = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        imagenIcono = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textFieldNuevoEmail = new javax.swing.JTextField();
        textFieldNuevaContraseña = new javax.swing.JTextField();
        textFieldNuevoPais = new javax.swing.JTextField();
        textFieldNuevoUsuario = new javax.swing.JTextField();
        comboBoxSexo = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fondoAzul2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1087, 615));
        setMinimumSize(new java.awt.Dimension(1087, 615));
        setPreferredSize(new java.awt.Dimension(1087, 615));
        setResizable(false);
        getContentPane().setLayout(null);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelPrincipal.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Trivia");
        panelPrincipal.add(jLabel6);
        jLabel6.setBounds(200, 0, 170, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/visualA.png"))); // NOI18N
        panelPrincipal.add(jLabel5);
        jLabel5.setBounds(-40, 50, 500, 460);

        jButton1.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jButton1.setText("Iniciar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton1);
        jButton1.setBounds(100, 520, 110, 40);

        jButton2.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jButton2.setText("Registrarse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton2);
        jButton2.setBounds(290, 520, 110, 40);

        fondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wallpaper azul.jpg"))); // NOI18N
        fondoAzul.setText("jLabel4");
        fondoAzul.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelPrincipal.add(fondoAzul);
        fondoAzul.setBounds(-920, -10, 1430, 630);

        getContentPane().add(panelPrincipal);
        panelPrincipal.setBounds(0, 0, 510, 620);

        panelLogIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelLogIn.setMaximumSize(new java.awt.Dimension(510, 620));
        panelLogIn.setMinimumSize(new java.awt.Dimension(0, 0));
        panelLogIn.setPreferredSize(new java.awt.Dimension(0, 0));
        panelLogIn.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña:");
        panelLogIn.add(jLabel7);
        jLabel7.setBounds(20, 300, 230, 70);

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Usuario:");
        panelLogIn.add(jLabel8);
        jLabel8.setBounds(80, 220, 170, 70);
        panelLogIn.add(textFieldUsuario);
        textFieldUsuario.setBounds(260, 240, 190, 40);
        panelLogIn.add(passwordFieldContraseña);
        passwordFieldContraseña.setBounds(260, 320, 190, 40);

        jButton3.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jButton3.setText("Iniciar Sesión");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelLogIn.add(jButton3);
        jButton3.setBounds(260, 400, 190, 40);

        jButton4.setBackground(new java.awt.Color(153, 0, 51));
        jButton4.setForeground(new java.awt.Color(153, 0, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelLogIn.add(jButton4);
        jButton4.setBounds(40, 490, 40, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoUsuario.png"))); // NOI18N
        panelLogIn.add(jLabel2);
        jLabel2.setBounds(220, 40, 220, 150);

        fondoAzul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wallpaper azul.jpg"))); // NOI18N
        fondoAzul1.setText("jLabel4");
        fondoAzul1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelLogIn.add(fondoAzul1);
        fondoAzul1.setBounds(-910, 0, 1430, 630);

        getContentPane().add(panelLogIn);
        panelLogIn.setBounds(0, 0, 0, 0);

        panelRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelRegistro.setMaximumSize(new java.awt.Dimension(510, 620));
        panelRegistro.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sexo:");
        panelRegistro.add(jLabel10);
        jLabel10.setBounds(190, 430, 90, 30);
        panelRegistro.add(textFieldNuevoNombre);
        textFieldNuevoNombre.setBounds(280, 230, 190, 30);

        jButton5.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/upload.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelRegistro.add(jButton5);
        jButton5.setBounds(340, 480, 70, 50);

        jButton6.setBackground(new java.awt.Color(153, 0, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelRegistro.add(jButton6);
        jButton6.setBounds(30, 490, 40, 30);

        imagenIcono.setForeground(new java.awt.Color(0, 0, 51));
        imagenIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoUsuario.png"))); // NOI18N
        imagenIcono.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRegistro.add(imagenIcono);
        imagenIcono.setBounds(310, 10, 132, 150);

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nombre :");
        panelRegistro.add(jLabel11);
        jLabel11.setBounds(150, 230, 130, 30);

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("E-mail:");
        panelRegistro.add(jLabel12);
        jLabel12.setBounds(170, 280, 110, 30);

        jLabel13.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("seleccionada:");
        panelRegistro.add(jLabel13);
        jLabel13.setBounds(90, 80, 280, 30);

        jLabel14.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Contraseña:");
        panelRegistro.add(jLabel14);
        jLabel14.setBounds(110, 330, 170, 29);

        jLabel15.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Fotografía:");
        panelRegistro.add(jLabel15);
        jLabel15.setBounds(130, 490, 150, 30);

        jLabel16.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("País:");
        panelRegistro.add(jLabel16);
        jLabel16.setBounds(200, 380, 80, 30);
        panelRegistro.add(textFieldNuevoEmail);
        textFieldNuevoEmail.setBounds(280, 280, 190, 30);
        panelRegistro.add(textFieldNuevaContraseña);
        textFieldNuevaContraseña.setBounds(280, 330, 190, 30);
        panelRegistro.add(textFieldNuevoPais);
        textFieldNuevoPais.setBounds(280, 380, 190, 30);
        panelRegistro.add(textFieldNuevoUsuario);
        textFieldNuevoUsuario.setBounds(280, 180, 190, 30);

        comboBoxSexo.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        comboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        panelRegistro.add(comboBoxSexo);
        comboBoxSexo.setBounds(280, 430, 190, 30);

        jButton8.setFont(new java.awt.Font("Rockwell", 1, 10)); // NOI18N
        jButton8.setText("Registrarse");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelRegistro.add(jButton8);
        jButton8.setBounds(280, 550, 190, 30);

        jLabel17.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Usuario:");
        panelRegistro.add(jLabel17);
        jLabel17.setBounds(160, 180, 110, 30);

        jLabel18.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Imagen");
        panelRegistro.add(jLabel18);
        jLabel18.setBounds(130, 40, 150, 50);

        fondoAzul2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wallpaper azul.jpg"))); // NOI18N
        fondoAzul2.setText("jLabel4");
        fondoAzul2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelRegistro.add(fondoAzul2);
        fondoAzul2.setBounds(-910, 0, 1430, 630);

        getContentPane().add(panelRegistro);
        panelRegistro.setBounds(0, 0, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Zabivaka.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 10, 500, 760);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wallpaper2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-400, -180, 1621, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setSize(0,0);
        panelLogIn.setSize(510, 620);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setSize(510, 620);
        panelRegistro.setSize(0,0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setSize(0,0);
        panelRegistro.setSize(510, 620);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(textFieldUsuario.getText().isEmpty() | passwordFieldContraseña.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Campo vacío.");
        }
        else {
            Usuario aux = Registros.getInstance().buscarUsuario(textFieldUsuario.getText());
            if (aux != null) {
                if (passwordFieldContraseña.getText().equals(aux.getContraseña())) {
                    Registros.getInstance().setUsuarioActual(aux);
                    VentanaCrearTorneo vTorneo = new VentanaCrearTorneo(aux);
                    vTorneo.setVisible(true);
                    this.dispose();
                } 
                else {
                    JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta.");
                }
            } 
            else {
                JOptionPane.showMessageDialog(rootPane, "Usuario no encontrado.");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        panelPrincipal.setSize(510, 620);
        panelLogIn.setSize(0,0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(textFieldNuevoUsuario.getText().isEmpty() | textFieldNuevoNombre.getText().isEmpty() | textFieldNuevoEmail.getText().isEmpty() | textFieldNuevaContraseña.getText().isEmpty() | textFieldNuevoPais.getText().isEmpty() | foto == null){
            JOptionPane.showMessageDialog(rootPane, "Campo vacío.");
        }
        else{
            Usuario aux = Registros.getInstance().buscarUsuario(textFieldNuevoUsuario.getText());
            if (aux!= null){
                JOptionPane.showMessageDialog(rootPane, "Ese usuario ya existe, intenta con " + textFieldNuevoUsuario.getText() + "123");
            }
            else{
                String nUsuario = textFieldNuevoUsuario.getText();
                String nNombre = textFieldNuevoNombre.getText();
                String nEmail = textFieldNuevoEmail.getText();
                String nContraseña = textFieldNuevaContraseña.getText();
                String nPais = textFieldNuevoPais.getText();
                String nSexo = comboBoxSexo.getSelectedItem().toString();
                Usuario nuevoUsuario = new Usuario(nNombre, nUsuario, nEmail, nContraseña, nPais, nSexo, foto);
                Registros.getInstance().listaUsuarios.add(nuevoUsuario);
                JOptionPane.showMessageDialog(rootPane, "Usuario: " + nUsuario + " registrado con éxito en el juego.");
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int resultado ;
        VentanaCargarArchivos ventana = new VentanaCargarArchivos();
        FileNameExtensionFilter filtro1 = new FileNameExtensionFilter("Fotos, JPG y PNG", "jpn","png");
        ventana.jFileCargarFoto.setFileFilter(filtro1);
        resultado = ventana.jFileCargarFoto.showOpenDialog(null);
        if(JFileChooser.APPROVE_OPTION == resultado){
            //guardar el archivo selecionado
            plan = ventana.jFileCargarFoto.getSelectedFile();
            try {
                ImageIcon icon = new ImageIcon(plan.toString());
                //ajustar el tamaño de la imagen que se ha cargado
                Icon fotoSubida = new ImageIcon(icon.getImage().getScaledInstance(imagenIcono.getWidth(), imagenIcono.getHeight(), Image.SCALE_DEFAULT));
                //borrar TEXTO en label
                imagenIcono.setText(null);
                //mostrar imagen en label
                imagenIcono.setIcon(fotoSubida);
                foto = (ImageIcon) fotoSubida; 
            } 
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Error al abrir la imagen " + ex);
            }
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxSexo;
    private javax.swing.JLabel fondoAzul;
    private javax.swing.JLabel fondoAzul1;
    private javax.swing.JLabel fondoAzul2;
    private javax.swing.JLabel imagenIcono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panelLogIn;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPasswordField passwordFieldContraseña;
    private javax.swing.JTextField textFieldNuevaContraseña;
    private javax.swing.JTextField textFieldNuevoEmail;
    private javax.swing.JTextField textFieldNuevoNombre;
    private javax.swing.JTextField textFieldNuevoPais;
    private javax.swing.JTextField textFieldNuevoUsuario;
    private javax.swing.JTextField textFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
